CI-CD-production-android
airqo-platform/AirQo-frontend pull request #1007
Opened 2023-01-05 11:38 UTC by Mnoble-19

#### Summary of Changes (What does this PR do?)

- Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [ ] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

#### Screenshots (optional)

2023-01-13 13:56 UTC, 123MwanjeMike requested changes
This is great work @Mnoble-19 
Just a one small thing missing

2023-01-13 13:56 UTC, 123MwanjeMike commented on .github/workflows/deploy-android-to-firebase-app-distribution.yml
> +    runs-on: ubuntu-latest
Could we add the line  `if: inputs.android == true` here just below the the job name. This tells the job to run when the box is checked

2023-01-13 13:56 UTC, 123MwanjeMike commented on .github/workflows/deploy-android-to-play-console.yml
> +    runs-on: ubuntu-latest
Same here

2023-01-25 10:09 UTC, 123MwanjeMike approved these changes
Thanks @Mnoble-19 
LGTM

2023-01-25 13:49 UTC, Baalmart approved these changes
LGTM

2023-01-25 13:51 UTC, merged