[MOBILE] Rename search bar widget
airqo-platform/AirQo-frontend pull request #1171
Opened 2023-05-13 08:52 UTC by Mnoble-19

#### Summary of Changes (What does this PR do?)
- Rename search bar widget to remove build error
<img width="1395" alt="Screenshot 2023-05-13 at 11 31 26" src="https://github.com/airqo-platform/AirQo-frontend/assets/60974514/12f7a40e-ef00-486c-84b2-b92f37e21f7c">

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Upgrade to the latest flutter version `flutter 3.10`
- run the app normally

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

#### Screenshots (optional)

2023-05-13 08:53 UTC, Mnoble-19 commented on mobile/pubspec.yaml
> +  intl: ^0.18.0
@NoahNsimbe I also changed this because the build was failing on my end when i used the initial one

2023-05-15 08:00 UTC, NoahNsimbe approved these changes
LGTM

2023-05-15 08:08 UTC, NoahNsimbe requested changes
Hi @Mnoble-19, thanks for the changes,

Please run `flutter analyze` and fix all issues caused by the upgrade.

2023-05-15 17:30 UTC, Baalmart approved these changes

2023-05-15 17:31 UTC, merged