[NetManager] Merge url configs and add PR template
airqo-platform/AirQo-frontend pull request #138
Opened 2020-09-14 15:40 UTC by ja-odur

#### Summary of Changes (What does this PR do?)
- Merged config urls into a single object for easy management.
- Adds a PR template.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Pull and checkout to this [branch](ft-set-location-defaults-plat-61) locally
* Install node requirements `npm install`
* Start the application `npm run prod-mac`
* You should be able to hit all the api services (in other words, the app should load all the data without any errors)
* Repeat the procedure for dev and staging environments.

#### What are the relevant tickets?
- [PLAT-117](https://airqoteam.atlassian.net/browse/PLAT-117)

#### Screenshots (optional)

2020-09-15 13:07 UTC, lilly-muyama requested changes
Please add run command for Windows too.

2020-09-15 13:14 UTC, ja-odur commented
> Please add run command for Windows too.

This has been fixed

2020-09-30 08:27 UTC, danielogen commented on netmanager/src/config/constants.js
> +      process.env.PROD_BASE_URL || "http://34.78.78.202/",
is it okay to treat `http://34.78.78.202/` as a constant and just call it here? -  I think it will make it cooler :)

2020-09-30 08:29 UTC, danielogen requested changes
Very clean and neat - I love it. Just some merge configs and suggestions left in the comment

2020-09-30 08:44 UTC, danielogen commented on netmanager/src/config/constants.js
> +      process.env.PROD_BASE_URL || "http://34.78.78.202/",
ok, I think this fine - no need to make changes

2020-09-30 09:59 UTC, lilly-muyama reviewed
@ja-odur please fix merge conflicts as suggested by @danielogen

2020-09-30 10:00 UTC, lilly-muyama commented
> 
> 
> @ja-odur please fix merge conflicts as suggested by @danielogen

Never mind, I see it's still a work in progress

2020-09-30 17:23 UTC, ja-odur commented
> @ja-odur please fix merge conflicts as suggested by @danielogen

@lilly-muyama @danielogen This has been fixed.

2020-10-01 12:41 UTC, Baalmart reviewed
Good stuff.
I guess we shall adopt this configuration change at beginning of next sprint - might cause some slight confusion now..

2021-04-29 13:18 UTC, lilly-muyama reviewed
I get this error @ja-odur 
![Screenshot_2021-04-29 NetManager](https://user-images.githubusercontent.com/26766933/116556755-7bfce000-a906-11eb-8db1-e79282b00e2f.png)

2021-04-29 13:44 UTC, sserurich approved these changes
LGTM.. works as expected

2021-05-05 11:49 UTC, danielogen approved these changes
Tested with both "http" and "https", works well.

2021-05-07 07:42 UTC, danielogen commented
> Good stuff.
> I guess we shall adopt this configuration change at beginning of next sprint - might cause some slight confusion now..

Alright, this is noted. Thanks @Baalmart . cc: @ja-odur

2021-05-07 08:31 UTC, danielogen commented
> > Good stuff.
> > I guess we shall adopt this configuration change at beginning of next sprint - might cause some slight confusion now..
> 
> Alright, this is noted. Thanks @Baalmart . cc: @ja-odur

Sorry, this was a very old review

2021-05-07 09:06 UTC, Priscilla-AL approved these changes

2021-05-07 09:25 UTC, merged