Web improvements
airqo-platform/AirQo-frontend pull request #1384
Opened 2023-07-31 08:17 UTC by OchiengPaul442

#### Summary of Changes (What does this PR do?)

- Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [ ] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

#### Screenshots (optional)

2023-08-01 14:47 UTC, Baalmart reviewed
thanks @OchiengPaul442 , this is good work. I have just left one small comment.
Additionally, now is a good time to start accompanying your new implementation with unit tests.

2023-08-01 14:47 UTC, Baalmart commented on website/frontend/src/components/Footer.js
> +          `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`
thanks @OchiengPaul442 ,can we have this url stored somewhere else? and just referenced here as a variable? In our codebase, do we have somewhere we keep such constants like urls? Thanks again!

2023-08-01 15:12 UTC, OchiengPaul442 commented
Thanks, @Martin Bbaale ***@***.***>, for your valuable feedback. Yes,
there is a URL file in the project, and will work on implementing this
change. and I forgot 😅 about the unit test, but I will implement that on
the next commit.

Thanks.

On Tue, 1 Aug 2023 at 17:48, Martin Bbaale ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> thanks @OchiengPaul442 <https://github.com/OchiengPaul442> , this is good
> work. I have just left one small comment.
> Additionally, now is a good time to start accompanying your new
> implementation with unit tests.
> ------------------------------
>
> In website/frontend/src/components/Footer.js
> <https://github.com/airqo-platform/AirQo-frontend/pull/1384#discussion_r1280751872>
> :
>
> > @@ -94,6 +96,83 @@ const Footer = () => {
>      setSelectedCountry(currentAirqloud);
>    }, [currentAirqloud]);
>
> +  useEffect(() => {
> +    const getUserCountryFromStorage = () => {
> +      const storedCountry = localStorage.getItem('userCountry');
> +      if (storedCountry) {
> +        dispatch(setCurrentAirQloudData(storedCountry));
> +      } else {
> +        getUserGeolocation();
> +      }
> +    };
> +
> +    // Function to fetch users country based on their IP address
> +    const getUserCountry = async (latitude, longitude) => {
> +      try {
> +        const response = await axios.get(
> +          `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en` <https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=$%7Blatitude%7D&longitude=$%7Blongitude%7D&localityLanguage=en>
>
> thanks @OchiengPaul442 <https://github.com/OchiengPaul442> ,can we have
> this url stored somewhere else? and just referenced here as a variable? In
> our codebase, do we have somewhere we keep such constants like urls? Thanks
> again!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/airqo-platform/AirQo-frontend/pull/1384#pullrequestreview-1557181194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXKGYDSHDSIUAEQKHNLFLN3XTEJKPANCNFSM6AAAAAA254MIHM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-08 12:12 UTC, Baalmart approved these changes

2023-08-08 12:16 UTC, Baalmart requested changes

2023-08-08 12:16 UTC, Baalmart commented on website/frontend/config/urls.js
> +export const LOCATIONS_TRACKING_URL = `${WEBSITE_BASE_URL}/https://api.bigdatacloud.net/data/reverse-geocode-client`;
please review this url, something is off here.

2023-08-08 12:22 UTC, Baalmart commented
@OchiengPaul442  , review why we are having the video in the landing page and yet it is not supposed to be in different PR?

2023-08-08 12:32 UTC, OchiengPaul442 commented
Thanks @Baalmart, working on it.

2023-08-09 08:37 UTC, closed without merging