[Netmanager] grids and cohorts analytics page and functionality
airqo-platform/AirQo-frontend pull request #1442
Opened 2023-08-24 20:12 UTC by Codebmk

#### Summary of Changes (What does this PR do?)

- Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [ ] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

#### Screenshots (optional)
![Screenshot from 2023-08-24 23-03-11](https://github.com/airqo-platform/AirQo-frontend/assets/46527380/c9f363e1-0908-47fd-bb78-345ce194bdb0)
![Screenshot from 2023-08-24 23-02-58](https://github.com/airqo-platform/AirQo-frontend/assets/46527380/d4afc3d1-965c-419d-909f-55051da9f2c7)
![Screenshot from 2023-08-24 22-59-28](https://github.com/airqo-platform/AirQo-frontend/assets/46527380/6ba9d4e6-bb41-4231-97b5-174c4e81653a)

2023-09-12 01:09 UTC, Codebmk commented
@Baalmart this PR is ready for review. Will be adding tests. Just want a first review and then make modifications including adding tests

2023-09-12 04:37 UTC, Baalmart commented
> @Baalmart this PR is ready for review. Will be adding tests. Just want a first review and then make modifications including adding tests

Thanks @Codebmk , let me review right away!

2023-09-12 05:13 UTC, Baalmart requested changes
Thanks @Codebmk ..... this is great work! Things look neat and mind blowing! Someone is surely putting in the work! :)

1. Using screenshots, I have been able to share the feedback via Slack DM.
2. As you also hinted, I am looking forward to the unit tests too. :)

2023-10-07 16:25 UTC, Baalmart approved these changes

2023-10-07 16:25 UTC, merged