[NetManager] Fix Jira support button issue
airqo-platform/AirQo-frontend pull request #193
Opened 2021-02-25 14:08 UTC by ja-odur

#### Summary of Changes (What does this PR do?)
- Add Jira support button on every page
-  Fixes this [issue](https://github.com/airqo-platform/AirQo-frontend/issues/192)

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?
- [PLAT-417](https://airqoteam.atlassian.net/browse/PLAT-417)

#### Screenshots (optional)

2021-02-25 14:15 UTC, danielogen approved these changes
Working well as expected. Thank for the fix @ja-odur

2021-02-26 02:44 UTC, Baalmart approved these changes
Looks good to me, I have just left a few comments....that might need to be transferred to issues I guess.

2021-02-26 02:44 UTC, Baalmart commented on netmanager/src/utils/customHooks.js
> +        "cf4a44fc-f333-4e48-8e6c-6b94f97cea15"
Are we supposed to have this key stored here? environmental variables perhaps?

2021-02-26 02:44 UTC, Baalmart commented on netmanager/src/App.js
> +        <Router>
Thanks, I guess we might have to move this router code to the Routers folder in the near future. Just to maintain a short and sweet App.js. :)

2021-02-26 02:45 UTC, Baalmart requested changes
But on second thought, I think we need to first address the security concern before we proceed with integration....

2021-02-26 07:39 UTC, ja-odur commented
> @Baalmart Since these keys are used on the altlassian page and they also provided script-tag with the same information to be embedded into html, I dont think it's a security threat but @danielogen can verify this.

@Baalmart Since these keys are used on the altlassian page and they also provided script-tag with the same information to be embedded into html, I dont think it's a security threat but @danielogen can verify this.

2021-02-26 07:47 UTC, Baalmart commented
Okay, let us wait for the verification, it will be interesting to learn about keys which are meant to be publicly accessible. Awaiting new thoughts/findings on this.

> @Baalmart Since these keys are used on the altlassian page and they also provided as script-tag with the same information to be embedded into html, I dont think it's a security threat but @danielogen can verify this.

2021-02-26 07:48 UTC, ja-odur commented
> Okay, let us wait for the verification, it will be interesting to learn about keys which are meant to be publicly accessible. Awaiting new thoughts/findings on this.
> 
> > @Baalmart Since these keys are used on the altlassian page and they also provided as script-tag with the same information to be embedded into html, I dont think it's a security threat but @danielogen can verify this.

Alright as we wait. Let me hide the keys

2021-02-26 07:54 UTC, danielogen commented
> > Okay, let us wait for the verification, it will be interesting to learn about keys which are meant to be publicly accessible. Awaiting new thoughts/findings on this.
> > > @Baalmart Since these keys are used on the altlassian page and they also provided as script-tag with the same information to be embedded into html, I dont think it's a security threat but @danielogen can verify this.
> 
> Alright as we wait. Let me hide the keys

I wasn't able to find any information about the key for now but I would suggest we go-ahead and hide it -  as I can see from some GitHub issues, guys are not revealing it either.

2021-02-26 08:00 UTC, ja-odur commented
@Baalmart @danielogen  I have hidden the key but we still have this information in other earlier branches. Not sure how we can resolve that.

2021-02-26 08:03 UTC, Baalmart commented
Thanks, I guess we shall rebase the rest of the branches immediately after we get this PR into staging....
> @Baalmart @danielogen I have hidden the key but we still have this information in other earlier branches. Not sure how we can resolve that.

2021-02-26 08:13 UTC, danielogen commented on netmanager/src/utils/customHooks.js
> +      jhdScript.setAttribute("data-key", process.env.REACT_APP_JIRA_KEY);
LGTM

2021-02-26 08:14 UTC, Baalmart approved these changes
Looks good, thanks.

2021-02-26 08:15 UTC, merged