Dan web
airqo-platform/AirQo-frontend pull request #2122
Opened 2024-07-30 16:15 UTC by danielmarv

#### Summary of Changes (What does this PR do?)

- I have introduced the web pack configurations so that we can optimize the loading speed of the site
- I have made quite a lot of changes to the code structure so that the thing can run well 

```shell
npm run web
``` 
- for the development

- and

```shell
npm run web-build 
``` 
- for the production 
- so this is a test out that why I did that so that you can test it out configuring it into the production pipeline

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

#### How should this be manually tested?

- Please include the steps to be done to setup and test this PR.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

#### Screenshots (optional)

2024-07-30 16:55 UTC, Baalmart reviewed
Thanks @danielmarv for this! 

- For some reason, I am not able to see the deploy preview LINK despite the successful build.
- Can you share the deploy preview link here?

2024-07-30 16:59 UTC, danielmarv commented
https://netmanager-preview-w7kzhvlewq-ew.a.run.app/

2024-07-30 17:13 UTC, Baalmart commented
> https://netmanager-preview-w7kzhvlewq-ew.a.run.app/

Thanks @danielmarv , how come I am not seeing it on my end. How did you manage to get it?

2024-07-30 17:15 UTC, danielmarv commented
Nop i had disabled them but am pushing a code to enable it @Baalmart

2024-07-30 17:17 UTC, Baalmart requested changes
Thanks @danielmarv ....also some new feedback for you to consider. See attached screenshots.
<img width="1112" alt="Screenshot 2024-07-30 at 20 14 23" src="https://github.com/user-attachments/assets/1fcd6a44-5de0-4a36-a490-df08368334a4">
<img width="1217" alt="Screenshot 2024-07-30 at 20 15 35" src="https://github.com/user-attachments/assets/2c37c46f-9032-4a10-9624-bfecbc93ba16">

2024-07-30 17:25 UTC, danielmarv commented
Yap that is the next step
coz the first step was to set up the deploy enironment
@Baalmart

2024-07-31 10:04 UTC, Baalmart commented
> Yap that is the next step coz the first step was to set up the deploy enironment @Baalmart

Alright @danielmarv , thanks for this.

2024-08-07 10:03 UTC, OchiengPaul442 commented
Hey @danielmarv,
Thanks for the changes, all seems to be working though there are a few issues, especially on the Locate view where it just shows a white screen and some few broken UIs that need fixing on some screens. please review the screen shows below.
![image](https://github.com/user-attachments/assets/922a8c9b-bf6e-404b-85eb-3e518b508ba6)
![image](https://github.com/user-attachments/assets/c35cf257-d385-4d63-8264-c41b1ae00f88)

2025-01-04 16:01 UTC, closed without merging

2025-01-04 16:01 UTC, Baalmart commented
Hi @danielmarv , thanks for this PR.

- At the moment, @Codebmk is migrating the Netmanager code to a new Next.js project. Please coordinate with her on the side accordingly as she continues setting up the new Next.js project.
- This means that we shall not need this optimisation since we plan to completely close this React.js project after the migration is done.
- On that note, I am closing this PR accordingly.

CC: @OchiengPaul442