Ft my places
airqo-platform/AirQo-frontend pull request #261
Opened 2021-05-18 10:45 UTC by NoahNsimbe

#### Summary of Changes (What does this PR do?)
- Enables search on my places list
- Replaces `Favourites` with `My Places`
- Disables displace of nodes that don't have the `last updated` value
- Fixes bugs caused by having different variable names pointing to the same functionality
- Adds secure storage of API keys

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
```
cd AirQo-frontend/mobile
```
Add `secret.ts` file to `src/providers/api` folder
Follow instructions in Readme.md on how to setup your environment and run the application

#### What are the relevant tickets?
- [PLAT-503](https://airqoteam.atlassian.net/browse/PLAT-503?atlOrigin=eyJpIjoiYmU3MWY4ZmIzMzdjNDE4MTkxMmNjNDNjN2JlZDRkNDQiLCJwIjoiaiJ9)
- [PLAT-542](https://airqoteam.atlassian.net/browse/PLAT-542?atlOrigin=eyJpIjoiMmIwYmVjZTJmNmNiNDYwZjkxYjA3ZDUwMGI3YmUyNmMiLCJwIjoiaiJ9)
- [PLAT-539](https://airqoteam.atlassian.net/browse/PLAT-539?atlOrigin=eyJpIjoiMzUwYWM0ZTBjNTBiNGVhYWI1MTM3NzlkYzlmYWMxY2QiLCJwIjoiaiJ9)
- [PLAT-540](https://airqoteam.atlassian.net/browse/PLAT-540?atlOrigin=eyJpIjoiZmM0MDA1MDUxZDNlNDc1MWJlOGVhMDhkMDJkZDBjZjEiLCJwIjoiaiJ9)

#### Screenshots (optional)

2021-05-20 04:29 UTC, danielogen reviewed
Tried testing this but am getting the error attached. I ran the following command after installing Cordova and Ionic globally: `npm install` and `ionic serve`.
![Screenshot 2021-05-20 at 07 25 37](https://user-images.githubusercontent.com/15224992/118919342-00a6b100-b93d-11eb-9b4a-ac4b0c385869.png)

2021-05-20 05:37 UTC, buzentech commented
> 
> 
> Tried testing this but am getting the error attached. I ran the following command after installing Cordova and Ionic globally: `npm install` and `ionic serve`.
> ![Screenshot 2021-05-20 at 07 25 37](https://user-images.githubusercontent.com/15224992/118919342-00a6b100-b93d-11eb-9b4a-ac4b0c385869.png)

Hello Daniel, 

Kindly reach out to Noah to provide you with that file.

2021-05-20 05:54 UTC, NoahNsimbe commented
> Tried testing this but am getting the error attached. I ran the following command after installing Cordova and Ionic globally: `npm install` and `ionic serve`.
> ![Screenshot 2021-05-20 at 07 25 37](https://user-images.githubusercontent.com/15224992/118919342-00a6b100-b93d-11eb-9b4a-ac4b0c385869.png)

@danielogen, please revisit the PR description, there are some instructions on how to get and where to put the `secret.ts` file. Going to reshare via slack

2021-05-20 06:32 UTC, danielogen commented
> > Tried testing this but am getting the error attached. I ran the following command after installing Cordova and Ionic globally: `npm install` and `ionic serve`.
> > ![Screenshot 2021-05-20 at 07 25 37](https://user-images.githubusercontent.com/15224992/118919342-00a6b100-b93d-11eb-9b4a-ac4b0c385869.png)
> 
> Hello Daniel,
> 
> Kindly reach out to Noah to provide you with that file.

Thanks all good now!

2021-05-20 06:33 UTC, danielogen commented
> > Tried testing this but am getting the error attached. I ran the following command after installing Cordova and Ionic globally: `npm install` and `ionic serve`.
> > ![Screenshot 2021-05-20 at 07 25 37](https://user-images.githubusercontent.com/15224992/118919342-00a6b100-b93d-11eb-9b4a-ac4b0c385869.png)
> 
> @danielogen, please revisit the PR description, there are some instructions on how to get and where to put the `secret.ts` file. Going to reshare via slack

Thanks @NoahNsimbe , its working well now

2021-05-20 06:34 UTC, danielogen requested changes
Working well, just one more change to make; "Saved Places" -> "My Places". See screenshot
![Screenshot 2021-05-20 at 09 20 29](https://user-images.githubusercontent.com/15224992/118930578-97c83480-b94e-11eb-81cf-7f9c37608b26.png)

2021-05-20 06:50 UTC, NoahNsimbe commented
> Working well, just one more change to make; "Saved Places" -> "My Places". See screenshot
> ![Screenshot 2021-05-20 at 09 20 29](https://user-images.githubusercontent.com/15224992/118930578-97c83480-b94e-11eb-81cf-7f9c37608b26.png)

Thanks @danielogen

2021-05-27 11:56 UTC, Baalmart approved these changes
LGTM to me, all notes in the PR description are present.

2021-05-27 11:59 UTC, Baalmart commented on mobile/src/pages/node/node.ts
> +          message: 'Up-to-date history information unavailable',
Just curious about how we can minimise this situation of not having up to date historical values. cc: @sserurich

2021-06-17 08:28 UTC, danielogen approved these changes
Hi @NoahNsimbe , things are working very well on my end. Just a quick inquiry: I see "My Location" and "My Places" -  I assume "My Location" is automatically inferred?

2021-06-17 08:28 UTC, danielogen commented
> Hi @NoahNsimbe , things are working very well on my end. Just a quick inquiry: I see "My Location" and "My Places" - I assume "My Location" is automatically inferred?

<img width="471" alt="Screen Shot 2021-06-17 at 11 22 52 AM" src="https://user-images.githubusercontent.com/15224992/122360529-4be7bb80-cf0b-11eb-8292-114882ab7950.png">

2021-06-18 06:14 UTC, Baalmart approved these changes
LGTM

2021-06-18 06:15 UTC, merged