full changes
airqo-platform/AirQo-frontend pull request #622
Opened 2022-05-18 14:14 UTC by Codebmk

#### Summary of Changes (What does this PR do?)
- Removed air quality reading from hero section
- Made hero section mobile responsive
- Made monitor section responsive
- Added new images on about us page

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Please include the steps to be done inorder to setup and test this PR.

#### Screenshots
![hero](https://user-images.githubusercontent.com/46527380/169057915-4e2b650c-c1ac-4f89-afe5-60f9c7b575bf.PNG)
![monitor](https://user-images.githubusercontent.com/46527380/169057958-67085416-4765-4676-ae2d-fb713f474962.PNG)

2022-05-18 14:41 UTC, 123MwanjeMike commented
Please note that this PR is a continuation of #618

2022-05-18 14:44 UTC, Codebmk commented
> Please note that this PR is a continuation of #618

Yes it is @123MwanjeMike thanks

2022-05-18 15:00 UTC, Codebmk commented on website/frontend/styles/Monitor.scss
> +@media (max-width: $mainBreakPoint) {
Adds mobile responsiveness to Monitor section

2022-05-18 15:01 UTC, Codebmk commented on website/frontend/styles/Hero.scss
> +@media(max-width: $mainBreakPoint) {
Adds mobile responsiveness to Hero section

2022-05-18 15:11 UTC, 123MwanjeMike commented
![image](https://user-images.githubusercontent.com/41787587/169075330-e81b0c71-c94d-49e0-9e4e-d85210170870.png)
![image](https://user-images.githubusercontent.com/41787587/169075549-28d15b48-41fd-4bf4-9c5a-d9e6a8beee0c.png)

Looks good, although it takes long to load

2022-05-18 15:12 UTC, Baalmart requested changes
Thanks for the changes. We are making great progress here! :)  I have just left a few comments for your review:

1. For the headshot images, thanks for the additions. Did we align with Zana which ones we shall use? 
2. Still on the images, what does this PR mean from the Optimisation standpoint? Aren't we supposed to reference these images from another service? Not sure how the discussion of images is going but gut feeling tells me that something needs to be reviewed here. cc: @123MwanjeMike 
3. Still on the images, wiil there be a corresponding backend for these additions? If yes, is this supposed to be a temporary hacky way of adding these images? cc: @FaithDaka 
4. I am still not getting the expected responsiveness. Perhaps it is my browswer or something. Awaiting your thoughts. Please check all the attached screenshots. 

Thanks again for the works, pretty impressive stuff! :)  @Codebmk 

<img width="848" alt="Screenshot 2022-05-18 at 18 02 20" src="https://user-images.githubusercontent.com/1590213/169075788-5e68f5bb-41c6-49f7-bb53-789db24ec033.png">
<img width="790" alt="Screenshot 2022-05-18 at 18 02 35" src="https://user-images.githubusercontent.com/1590213/169075809-a0f15883-b2c5-4c3f-ab65-4c49be6c5569.png">
<img width="693" alt="Screenshot 2022-05-18 at 18 02 56" src="https://user-images.githubusercontent.com/1590213/169075812-df9405e6-1e45-45a4-9597-f9cc3813b51f.png">
<img width="705" alt="Screenshot 2022-05-18 at 18 03 09" src="https://user-images.githubusercontent.com/1590213/169075819-5e7fb989-7e81-45a0-af1c-20d59fea59bd.png">
<img width="721" alt="Screenshot 2022-05-18 at 18 03 28" src="https://user-images.githubusercontent.com/1590213/169075827-a63a8cbd-f57b-4deb-9d4c-d74127ae1749.png">
<img width="618" alt="Screenshot 2022-05-18 at 18 03 45" src="https://user-images.githubusercontent.com/1590213/169075829-e5666917-31eb-41e3-96e4-87af0b092d6b.png">
<img width="826" alt="Screenshot 2022-05-18 at 18 04 06" src="https://user-images.githubusercontent.com/1590213/169075833-3334bd69-d88a-46ad-ae13-bb7cc684b8a0.png">
<img width="580" alt="Screenshot 2022-05-18 at 18 04 22" src="https://user-images.githubusercontent.com/1590213/169075840-8f74dfeb-8ad3-4388-b2ef-26dc768de792.png">

2022-05-18 15:17 UTC, 123MwanjeMike commented
> Thanks for the changes. We are making great progress here! :) I have just left a few comments for your review:
> 
>     1. For the headshot images, thanks for the additions. Did we align with Zana which ones we shall use?
> 
>     2. Still on the images, what does this PR mean from the Optimisation standpoint? Aren't we supposed to reference these images from another service? Not sure how the discussion of images is going but gut feeling tells me that something needs to be reviewed here. cc: @123MwanjeMike
> 
>     3. Still on the images, wiil there be a corresponding backend for these additions? If yes, is this supposed to be a temporary hacky way of adding these images? cc: @FaithDaka
> 
>     4. I am still not getting the expected responsiveness. Perhaps it is my browswer or something. Awaiting your thoughts. Please check all the attached screenshots.
> 
> 
> Thanks again for the works, pretty impressive stuff! :) @Codebmk
> 
> <img alt="Screenshot 2022-05-18 at 18 02 20" width="848" src="https://user-images.githubusercontent.com/1590213/169075788-5e68f5bb-41c6-49f7-bb53-789db24ec033.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 02 35" width="790" src="https://user-images.githubusercontent.com/1590213/169075809-a0f15883-b2c5-4c3f-ab65-4c49be6c5569.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 02 56" width="693" src="https://user-images.githubusercontent.com/1590213/169075812-df9405e6-1e45-45a4-9597-f9cc3813b51f.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 03 09" width="705" src="https://user-images.githubusercontent.com/1590213/169075819-5e7fb989-7e81-45a0-af1c-20d59fea59bd.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 03 28" width="721" src="https://user-images.githubusercontent.com/1590213/169075827-a63a8cbd-f57b-4deb-9d4c-d74127ae1749.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 03 45" width="618" src="https://user-images.githubusercontent.com/1590213/169075829-e5666917-31eb-41e3-96e4-87af0b092d6b.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 04 06" width="826" src="https://user-images.githubusercontent.com/1590213/169075833-3334bd69-d88a-46ad-ae13-bb7cc684b8a0.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 04 22" width="580" src="https://user-images.githubusercontent.com/1590213/169075840-8f74dfeb-8ad3-4388-b2ef-26dc768de792.png">

For the images, I suggest using Cloudinary moving forward. I anticipate many more images will be coming in with time. @Codebmk is that up for consideration?

2022-05-18 15:21 UTC, Baalmart reviewed
Hi @Codebmk , please ignore my earlier comments about responsiveness.

At the moment, it is just not responsive on Surface pro., I-pad and other corresponding Tablet variations.

So you can focus on review my other feedback points. Thanks!

2022-05-18 15:22 UTC, Baalmart commented
> Hi @Codebmk , please ignore my earlier comments about responsiveness.
> 
> At the moment, it is just not responsive on Surface pro., I-pad and other corresponding Tablet variations.
> 
> So you can focus on review my other feedback points. Thanks!

I had to pull your latest changes. :) @Codebmk

2022-05-18 15:24 UTC, Codebmk commented
> > Thanks for the changes. We are making great progress here! :) I have just left a few comments for your review:
> > ```
> > 1. For the headshot images, thanks for the additions. Did we align with Zana which ones we shall use?
> > 
> > 2. Still on the images, what does this PR mean from the Optimisation standpoint? Aren't we supposed to reference these images from another service? Not sure how the discussion of images is going but gut feeling tells me that something needs to be reviewed here. cc: @123MwanjeMike
> > 
> > 3. Still on the images, wiil there be a corresponding backend for these additions? If yes, is this supposed to be a temporary hacky way of adding these images? cc: @FaithDaka
> > 
> > 4. I am still not getting the expected responsiveness. Perhaps it is my browswer or something. Awaiting your thoughts. Please check all the attached screenshots.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks again for the works, pretty impressive stuff! :) @Codebmk
> > <img alt="Screenshot 2022-05-18 at 18 02 20" width="848" src="https://user-images.githubusercontent.com/1590213/169075788-5e68f5bb-41c6-49f7-bb53-789db24ec033.png">
> > <img alt="Screenshot 2022-05-18 at 18 02 35" width="790" src="https://user-images.githubusercontent.com/1590213/169075809-a0f15883-b2c5-4c3f-ab65-4c49be6c5569.png">
> > <img alt="Screenshot 2022-05-18 at 18 02 56" width="693" src="https://user-images.githubusercontent.com/1590213/169075812-df9405e6-1e45-45a4-9597-f9cc3813b51f.png">
> > <img alt="Screenshot 2022-05-18 at 18 03 09" width="705" src="https://user-images.githubusercontent.com/1590213/169075819-5e7fb989-7e81-45a0-af1c-20d59fea59bd.png">
> > <img alt="Screenshot 2022-05-18 at 18 03 28" width="721" src="https://user-images.githubusercontent.com/1590213/169075827-a63a8cbd-f57b-4deb-9d4c-d74127ae1749.png">
> > <img alt="Screenshot 2022-05-18 at 18 03 45" width="618" src="https://user-images.githubusercontent.com/1590213/169075829-e5666917-31eb-41e3-96e4-87af0b092d6b.png">
> > <img alt="Screenshot 2022-05-18 at 18 04 06" width="826" src="https://user-images.githubusercontent.com/1590213/169075833-3334bd69-d88a-46ad-ae13-bb7cc684b8a0.png">
> > <img alt="Screenshot 2022-05-18 at 18 04 22" width="580" src="https://user-images.githubusercontent.com/1590213/169075840-8f74dfeb-8ad3-4388-b2ef-26dc768de792.png">
> 
> For the images, I suggest using Cloudinary moving forward. I anticipate many more images will be coming in with time. @Codebmk is that up for consideration?

@123MwanjeMike yes there's a number of options to use. Though sounds like a decision where we need to involve @ja-odur .

2022-05-18 15:25 UTC, 123MwanjeMike requested changes
All looks good to me, but is there a way we can speed up the loading by reducing the size of the entrypoint file? 

![image](https://user-images.githubusercontent.com/41787587/169080502-2b50f93a-06b8-4ea3-a98f-82193f46333c.png)

2022-05-18 17:16 UTC, Baalmart commented
> > 1. For the headshot images, thanks for the additions. Did we align with Zana which ones we shall use?
> 
> @Baalmart We are using the exterior images

Although I saw people';s pictures in the PR, did not investigate. So thought the PR also uploads the images. :)

2022-05-20 14:01 UTC, Baalmart reviewed
Hi @Codebmk , still seeing images in the assets. Is this the intended approach? See attached screenshot for details.
<img width="1003" alt="Screenshot 2022-05-20 at 16 49 04" src="https://user-images.githubusercontent.com/1590213/169544364-ad23e0c5-d4d2-4f22-bd3b-1052edafe7d4.png">

2022-05-20 14:14 UTC, Baalmart reviewed
Thanks @Codebmk , all the topics mentioned in the PR description are worked on as mentioned. Thanks!

Just another observation, looks like the famous main.bundle is relatively big.....please review and share thoughts. See attached screenshot. cc: @123MwanjeMike 
<img width="1340" alt="Screenshot 2022-05-20 at 17 11 38" src="https://user-images.githubusercontent.com/1590213/169546712-5304b78c-eb2f-4d85-9474-4ac52b2d79cf.png">

2022-05-27 14:47 UTC, Baalmart commented
> Thanks for the changes. We are making great progress here! :) I have just left a few comments for your review:
> 
> 1. For the headshot images, thanks for the additions. Did we align with Zana which ones we shall use?
> 2. Still on the images, what does this PR mean from the Optimisation standpoint? Aren't we supposed to reference these images from another service? Not sure how the discussion of images is going but gut feeling tells me that something needs to be reviewed here. cc: @123MwanjeMike
> 3. Still on the images, wiil there be a corresponding backend for these additions? If yes, is this supposed to be a temporary hacky way of adding these images? cc: @FaithDaka
> 4. I am still not getting the expected responsiveness. Perhaps it is my browswer or something. Awaiting your thoughts. Please check all the attached screenshots.
> 
> Thanks again for the works, pretty impressive stuff! :) @Codebmk
> 
> <img alt="Screenshot 2022-05-18 at 18 02 20" width="848" src="https://user-images.githubusercontent.com/1590213/169075788-5e68f5bb-41c6-49f7-bb53-789db24ec033.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 02 35" width="790" src="https://user-images.githubusercontent.com/1590213/169075809-a0f15883-b2c5-4c3f-ab65-4c49be6c5569.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 02 56" width="693" src="https://user-images.githubusercontent.com/1590213/169075812-df9405e6-1e45-45a4-9597-f9cc3813b51f.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 03 09" width="705" src="https://user-images.githubusercontent.com/1590213/169075819-5e7fb989-7e81-45a0-af1c-20d59fea59bd.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 03 28" width="721" src="https://user-images.githubusercontent.com/1590213/169075827-a63a8cbd-f57b-4deb-9d4c-d74127ae1749.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 03 45" width="618" src="https://user-images.githubusercontent.com/1590213/169075829-e5666917-31eb-41e3-96e4-87af0b092d6b.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 04 06" width="826" src="https://user-images.githubusercontent.com/1590213/169075833-3334bd69-d88a-46ad-ae13-bb7cc684b8a0.png">
> 
> <img alt="Screenshot 2022-05-18 at 18 04 22" width="580" src="https://user-images.githubusercontent.com/1590213/169075840-8f74dfeb-8ad3-4388-b2ef-26dc768de792.png">

Thanks @Codebmk ........
Just have one more clarification on the images, will there be a corresponding backend for these image additions for profile and etc? If yes, is this supposed to be a temporary "hacky" way of adding these images? cc: @FaithDaka @ja-odur

2022-05-30 06:20 UTC, Codebmk commented
> Thanks @Codebmk ........
Just have one more clarification on the images, will there be a corresponding backend for these image additions for profile and etc? If yes, is this supposed to be a temporary "hacky" way of adding these images? cc: @FaithDaka @ja-odur

Yes @Baalmart it is temporary. There;s more images that are gonna be coming in so for now it seems best to use the current implementation

2022-05-30 10:10 UTC, 123MwanjeMike requested changes
The social media links on the footer work, but the twitter links on the individual profiles aren't working

2022-05-30 19:00 UTC, ja-odur reviewed
@Codebmk Static files have been removed on the staging branch. Update this PR so that the files changed are clear.

2022-06-01 06:11 UTC, ja-odur approved these changes
LGTM

2022-06-01 06:12 UTC, merged