[Website] Ft Highlights Section Backend
airqo-platform/AirQo-frontend pull request #724
Opened 2022-07-18 07:39 UTC by FaithDaka

#### Summary of Changes (What does this PR do?)
- Features the backend setup for the highlights section of the homepage.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch and checkout _ft-backend_ to run the updated admin portal.

#### What are the relevant tickets?
- [WEB-270]

#### Screenshots
![Screenshot from 2022-07-18 10-18-35](https://user-images.githubusercontent.com/53012890/179464714-6f79007b-4207-488e-bd72-02b33c429a87.png)

[WEB-270]: https://airqoteam.atlassian.net/browse/WEB-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-07-18 10:41 UTC, 123MwanjeMike approved these changes

2022-07-19 18:55 UTC, ja-odur requested changes
Left a few comments. On top of that, please delete the static files. Both collected statics and frontend static.

2022-07-19 18:55 UTC, ja-odur commented on website/backend/highlights/models.py
> +class Tag(TimeStampedModel):
Use the `BaseModel` from `backend.utils.model`

2022-07-19 18:55 UTC, ja-odur commented on website/backend/highlights/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
When inheriting from the `BaseModel` or `TimeStampedModel`, the created_at and updated_at fields are auto added for you.

2022-07-19 18:55 UTC, ja-odur commented on website/backend/highlights/models.py
> +class Highlight(TimeStampedModel):
Use BaseModel here too

2022-07-19 18:55 UTC, ja-odur commented on website/backend/highlights/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
THese fields are auto added

2022-07-20 18:49 UTC, ja-odur requested changes
@FaithDaka Why are css files deleted (frontend/styles/lib)? These are imported in the scss files

2022-07-20 18:59 UTC, FaithDaka commented
Were the css files under a static folder? Because everything in a “static” directory was removed from this branch’s index. That’s all I specified in the gitignore file.

2022-07-20 19:19 UTC, ja-odur commented
Check the changed files. The deleted scss files are from `frontend/styles/lib/ directory. They are critical scss files.

2022-07-21 05:40 UTC, FaithDaka commented
@ja-odur **Line 17** in the _.gitignore_  file ignores all files in a lib/ directory, so reinforcing it must have deleted them from this branch to stop being tracked. But they are not deleted from my local machine.
Changing the directory name would mean changing it wherever it appears, so what should be done?

2022-07-21 08:15 UTC, merged