move to production
airqo-platform/AirQo-frontend pull request #741
Opened 2022-07-29 06:39 UTC by Baalmart

#### Summary of Changes (What does this PR do?)
move to production

2022-08-03 08:13 UTC, Baalmart reviewed
Thanks @Codebmk for this. Let us monitor the effects of this changes in production mode. Thanks! cc: @123MwanjeMike

2022-08-03 08:13 UTC, Baalmart commented on netmanager/src/views/pages/Download/Download.js
> +    e.preventDefault();
I am about to merge this one in since it is just an addition of a new function. I do not foresee any problems. @123MwanjeMike @Codebmk @FaithDaka

2022-08-12 13:58 UTC, 123MwanjeMike requested changes
Great work team.

2022-08-12 13:58 UTC, 123MwanjeMike commented on mobile/lib/firebase_options.dart
>      databaseURL: 'https://airqo-250220.firebaseio.com',
We have a couple of exposed values in the `FirebaseOptions` function that I feel would be best fit if added to the .env file. Could we review this approach of hard coding them before moving to production?
cc @Mnoble-19 @BenjaminSsempala @NoahNsimbe

2022-08-25 06:09 UTC, merged