Ft next platform cicd
airqo-platform/AirQo-frontend pull request #758
Opened 2022-08-16 13:14 UTC by 123MwanjeMike

#### Summary of Changes (What does this PR do?)
- Adds ci/cd for the new platform

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?
- [ticket_id]()

#### Screenshots (optional)

2022-08-16 15:02 UTC, Baalmart requested changes
Thanks for the great works @123MwanjeMike 
Please create a new PR. Your PR base branch is the same as the source of the changes.

2022-08-16 15:07 UTC, 123MwanjeMike commented
> Thanks for the great works @123MwanjeMike
> Please create a new PR. Your PR base branch is the same as the source of the changes.

This PR is a build up [to this PR](https://github.com/airqo-platform/AirQo-frontend/pull/759). The base is intentionally not staging.

2022-08-17 07:01 UTC, 123MwanjeMike commented on k8s/platform/prod-airqo-next-platform.yaml
> +          image: us.gcr.io/airqo-250220/airqo-next-platform:latest
Hi @NoahNsimbe 
The image is built from the production deploy workflow. This is the file
https://github.com/airqo-platform/AirQo-frontend/blob/bf94e359951dcbcd4eb16b9fc8118f69467d7f01/.github/workflows/deploy-frontends-to-production.yml#L312

2022-08-17 07:07 UTC, NoahNsimbe commented on k8s/platform/prod-airqo-next-platform.yaml
> +          image: us.gcr.io/airqo-250220/airqo-next-platform:latest
great

2022-08-17 13:29 UTC, Baalmart commented
> > Thanks for the great works @123MwanjeMike
> > Please create a new PR. Your PR base branch is the same as the source of the changes.
> 
> This PR is a build up [to this other PR](https://github.com/airqo-platform/AirQo-frontend/pull/759). The base is intentionally not staging. cc @Baalmart

Alright @123MwanjeMike , I am still curious about this Git workflow. How does our Github policy relate with this workflow taken here?

As always, I usually discourage any "unique awesome ways" of doing things. These unique and awesome Git workflows usually bring avoidable problems in the near future.

2022-08-19 13:50 UTC, merged