[Website]Added api auth
airqo-platform/AirQo-frontend pull request #813
Opened 2022-09-21 12:55 UTC by Codebmk

#### Summary of Changes (What does this PR do?)
- Added Authorizathion header to API endpoints

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?
- [WEB-323](https://airqoteam.atlassian.net/browse/WEB-323)

2022-09-21 13:48 UTC, 123MwanjeMike requested changes

2022-09-21 13:48 UTC, 123MwanjeMike commented on website/frontend/apis/index.js
> +    await axios.get(AIRQLOUD_SUMMARY, { headers }).then((response) => response.data);
Thanks @Codebmk 
However, this will fail given that the Authorization is not passed in the headers object but rather as a plain variable

2022-09-22 05:41 UTC, 123MwanjeMike commented
Related to [this backend PR](https://github.com/airqo-platform/AirQo-api/pull/1011)

2022-09-22 09:32 UTC, Codebmk commented
@Baalmart @FaithDaka @NoahNsimbe please review. The errors have been resolved. Thanks. cc: @123MwanjeMike

2022-09-22 10:05 UTC, 123MwanjeMike commented on calibrate/src/views/apis/calibrateTool.js
> +axios.defaults.headers.common.Authorization =
[calibrate app API auth](https://github.com/airqo-platform/AirQo-frontend/pull/813/commits/a2e91d147686f65632de981d7e5eee21c70da82a)

2022-09-22 10:05 UTC, 123MwanjeMike commented on website/frontend/apis/index.js
> +} from '../config/urls';
[remove duplicate imports](https://github.com/airqo-platform/AirQo-frontend/pull/813/commits/59f352e198a04b4140b6971ddc53a6754189e8ce)

2022-09-22 10:06 UTC, 123MwanjeMike approved these changes
LGTM

2022-09-22 10:30 UTC, 123MwanjeMike commented on .github/workflows/deploy-frontends-to-production.yml
> +          --build-arg REACT_APP_AUTHORIZATION_TOKEN=${{ secrets.WEBSITE_PROD_REACT_APP_AUTHORIZATION_TOKEN }} \
[add REACT_APP_AUTHORIZATION_TOKEN to build pipeline](https://github.com/airqo-platform/AirQo-frontend/pull/813/commits/c758612860fa93ab7aa1d5462de2f33a15a5523f)

2022-09-22 10:30 UTC, 123MwanjeMike commented on .github/workflows/deploy-frontend-to-preview-env.yml
> +          cd calibrate/
[fix deploy preview build path](https://github.com/airqo-platform/AirQo-frontend/pull/813/commits/1ca55d44fe6f10ab6a1214d19ddae5e0a3679a53)

2022-09-22 11:55 UTC, merged