[Analytics] Implement analytics navigation
airqo-platform/AirQo-frontend pull request #836
Opened 2022-10-05 15:59 UTC by Codebmk

#### Summary of Changes (What does this PR do?)
- Includes a top navbar and a sidebar. Added some makeshift responsiveness where a menu button shows/hides the sidebar.
- Updated the absolute imports config to include imports from the public folder--initially it was only looking at the src.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* git pull origin staging
* git checkout ft-aq-analytics-nav
* yarn install
* yarn add
* Open http://localhost:3000 . The Analytics dropdown item in the sidebar is active. You can toggle it and select the airqlouds option to navigate to the airqlouds page

#### What are the relevant tickets?
- [AN-137](https://airqoteam.atlassian.net/browse/AN-137)

#### Screenshots
![aq_nav_structure_3](https://user-images.githubusercontent.com/46527380/194106131-139b6c14-ed6b-4ca0-9673-c693d0bf02f3.png)
![aq_nav_structure_2](https://user-images.githubusercontent.com/46527380/194106145-bb1cdaef-fd20-4009-aefd-31f514a66e4e.png)
![aq_nav_structure_1](https://user-images.githubusercontent.com/46527380/194106149-75b2e8fe-69d5-44e3-97d7-d91a1a3d9d4a.png)

2022-10-06 10:12 UTC, 123MwanjeMike requested changes
![image](https://user-images.githubusercontent.com/41787587/194287311-14893708-6399-4d47-b92e-e3003118f179.png)
Great progress @Codebmk 

**I however notice the tests are failing cause of an import configuration. Could you look into it?**
![image](https://user-images.githubusercontent.com/41787587/194287004-d52fa8c1-c6d9-4c65-9ec8-8794ad6f9e40.png)

2022-10-06 11:58 UTC, BenjaminSsempala approved these changes
LGTM

2022-10-07 14:11 UTC, 123MwanjeMike approved these changes
Great work @Codebmk, the tests workflow is now passing.
LGTM

2022-10-07 14:11 UTC, Codebmk commented on platform/.eslintrc.json
> +        "config": "jsconfig.json"
This imports the aliases from the paths in the jsconfig.json

2022-10-10 12:34 UTC, FaithDaka approved these changes

2022-10-10 14:19 UTC, merged