Creating .env.sample file and updating README.md according to it.
airqo-platform/AirQo-frontend pull request #896
Opened 2022-10-25 15:42 UTC by rohitkori

#### Summary of Changes (What does this PR do?)
- Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?
- [ticket_id]()

#### Screenshots (optional)

2022-10-26 12:46 UTC, 123MwanjeMike requested changes
Good work @rohitkori.
However, these changes need to be implemented in the [netmanager folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/netmanager). Could you make that change so it's all good to review and merge.
When ready, check the respective boxes in the PR description for reviewers to know the readiness state of the PR.
Thank you.

2022-10-26 21:30 UTC, rohitkori commented on README.md
> +You need to fill actual values to the environment variables while creating the respective `.env` file from `.env.sample` file
okk sure

2022-10-26 21:33 UTC, rohitkori commented on README.md
> +You need to fill actual values to the environment variables while creating the respective `.env` file from `.env.sample` file
I had done the change specified by you. Please review it.

2022-10-27 07:07 UTC, 123MwanjeMike commented on README.md
> +You need to fill actual values to the environment variables while creating the respective `.env` file from `.env.sample` file
Thank you @rohitkori 
However, the `.env.sample` file is supposed to be added the netmanager folder(https://github.com/rohitkori/AirQo-frontend/tree/staging/netmanager). Also, the changes in the README are supposed to be made to the netmanager README(https://github.com/rohitkori/AirQo-frontend/blob/staging/netmanager/README.md) not the one at repository root(https://github.com/rohitkori/AirQo-frontend/blob/staging/netmanager/README.md).

Please make make this migration and it'll be perfect.

2022-10-27 07:11 UTC, 123MwanjeMike reviewed
Thank you @rohitkori 
Just a guiding comment

2022-10-27 07:11 UTC, 123MwanjeMike commented on README.md
> +
Please move this change to this line of the netmanager README https://github.com/rohitkori/AirQo-frontend/blob/bd7cab7856e425c5722e650a363eea310a91dc78/netmanager/README.md?plain=1#L9

2022-11-02 13:40 UTC, closed without merging

2022-11-02 14:42 UTC, 123MwanjeMike commented
Implementation of this PR is carried to #917
cc @rohitkori