[CI/942]: Update actions checkout version from v2 to v3
airqo-platform/AirQo-frontend pull request #944
Opened 2022-11-12 04:52 UTC by Vinitvh

#### Summary of Changes (What does this PR do?)

- Updated actions checkout version from `v2` to use `v3` following `Nodejs 12 actions are deprecated` warning from GitHub.
- Updated `setup-node` to `v3` with node version `16`

#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [x] I've included the issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done in order to set up and test this PR.

#### What are the relevant tickets?

- Closes #942

#### Screenshots (optional)

2022-11-14 09:00 UTC, 123MwanjeMike requested changes
Thanks @Vinitvh 

I however have a small request. Could we keep the node version we are using to build the docker images 12 given that the main complaint only came from the checkout action.

Thus, kindly revert the changes to the (actions/setup-node@v2)sections below.

![image](https://user-images.githubusercontent.com/41787587/201617004-b461b5f6-425f-4c8b-a0aa-d65b7c633d0a.png)

2022-11-14 09:00 UTC, 123MwanjeMike commented on .github/workflows/deploy-frontend-pr-previews.yml
> +          node-version: "16"
This one

2022-11-14 09:00 UTC, 123MwanjeMike commented on .github/workflows/deploy-frontends-to-production.yml
> +          node-version: "16"
This one too

2022-11-14 09:00 UTC, 123MwanjeMike commented on .github/workflows/deploy-frontends-to-staging.yml
> +          node-version: "16"
Here too

2022-11-14 17:48 UTC, 123MwanjeMike approved these changes
Thanks @Vinitvh 
LGTM

2022-11-17 06:33 UTC, Baalmart approved these changes
LGTM, thanks @Vinitvh

2022-11-17 09:46 UTC, merged